version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app            # mount source code for live reload
      - /app/node_modules         # avoid overriding node_modules
    environment:
      - PORT=${PORT}
      - MONGO_URL=MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    command: npm run dev          # 👈 override CMD if needed

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
